name: Invite
version: ${project.version}
main: com.github.justadeni.invite.Invite
bootstrapper: com.github.justadeni.invite.InviteBootstrap
api-version: '1.21'
authors: [ justADeni ]
description: Invite your friends to the server

dependencies:
  server:
    simplewhitelist:
      load: BEFORE
      required: true
      join-classpath: true

permissions:
  invite.use:
    description: "Use of /invite command"
    default: true
  invite.reload:
    description: "Use of /invite reload"
    default: op
  invite.bypass:
    description: "Bypass restrictions on number of invites"
    default: op
  invite.uninvite.own:
    description: "Uninvite player you invited"
    default: true
  invite.uninvite.all:
    description: "Uninvite any player"
    default: op